version: "3"
services:
  test:
    build:
      context: .
      args:
        - env=test
    volumes:
      - ${PWD}:/app
    ports:
      - 5100:5100
    environment:
      - MONGODB_URI=mongodb://user:secret@mongodb:27017/default
      - DATABASE=default
      - TABLE_USERS=users
    depends_on:
      - mongodb
    entrypoint: pytest -v