version: "3"
services:
  flask-auth:
    build: .
    volumes:
      - ${PWD}:/app
    ports:
      - 5100:5100
    environment:
      - MONGODB_URI=mongodb://user:secret@mongodb:27017/default
      - DATABASE=default
      - TABLE_USERS=users
    depends_on:
      - mongodb
  mongodb:
    image: bitnami/mongodb:4.1.8
    expose:
      - 27017
    environment:
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGODB_DATABASE=default
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=secret
